# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SoggyOnion
version:      0.01
version_from: lib/SoggyOnion.pm
installdirs:  site
requires:
    Cache::FileCache:              File::Basename
    File::Find::Rule:              File::Path
    Geo::Weather:                  HTML::Entities
    HTML::Strip:                   HTML::TokeParser
    IO::All:                       IO::Scalar
    LWP::Simple:                   Parallel::ForkManager
    Template:                      Test::More
    XML::RSS:                      YAML

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
